name: PYTHON

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
    - uses: jiro4989/setup-nim-action@v1.0.2
      with:
        nim-version: '1.2.0'

    - name: Update Python PIP
      run: pip install --upgrade --disable-pip-version-check pip

    - name: Cache nimble
      id: cache-nimble
      uses: actions/cache@v1
      with:
        path: ~/.nimble
        key: ${{ runner.os }}-nimble-$CHOOSENIM_CHOOSE_VERSION

    - name: Nimble Refresh
      run: |
        export PATH=$HOME/.nimble/bin:$PATH
        nimble -y refresh

    - name: Nimble Install dependencies
      run: |
        export PATH=$HOME/.nimble/bin:$PATH
        nimble -y install nimpy

    - name: Compile DEBUG Mode
      run: |
        export PATH=$HOME/.nimble/bin:$PATH
        nim c -d:ssl --app:lib --threads:on --out:faster_than_requests.so faster_than_requests.nim

    - name: Compile RELEASE Mode
      run: |
        export PATH=$HOME/.nimble/bin:$PATH
        nim c --app:lib --threads:on -d:release -d:danger -d:ssl --out:faster_than_requests.so faster_than_requests.nim

    - name: Strip Binary
      run: strip --strip-all faster_than_requests.so

    - name: Import Binary
      run: python3 -c "import faster_than_requests"

    - name: Unittests
      run: |
        cp -v faster_than_requests.so tests/faster_than_requests.so
        python3 tests/tests.py
